export { Home } from './screens/Home/Home'
export { Header } from './screens/Header/Header'
export { SignUp } from './screens/Cadastro/Cadastro'
export { SignIn } from './screens/SignIn/SignIn'
export { Carousel } from './screens/Carousel/Carrossel'
export { Benefits } from './screens/Home/Benefits/Beneficios'
export { Footer } from './screens/Footer/Footer'
export { Content } from './screens/Home/Content/Conteudo'
export { Instituicoes } from './screens/Instituicoes/Instituicoes'
export { SignupInstituicao } from './screens/Cadastro/SignupInstituicao'
export { SignupUser } from './screens/Cadastro/CadastroUsuario'
export {InstituicoesExemplo} from './screens/Home/InstituicoesExemplo/InstituicoesExemplo'
